Feature/rf50
Aast12/expoingenieriaswebapp pull request #8
Opened 2022-11-10 19:29 UTC by JeG99

- Se agregó el menú de Miembros de comité para usuarios administradores
- `can_approve_committee_members` está siendo correctamente usado desde la vista detallada (_form) del menú de miembros de comité  
- Se usa la propiedad `active` para mostrar la lista de miembros de comité en el menú de miembros de comité

TODO:
- Por ahora la lista de miembros de comité solo muestra una entrada porque no se están creando miembros de comité al seleccionarlos en el menú de usuarios, solo se activan atributos. Hace falta ver un modo de mostrar a todos los miembros con sus respectivos atributos (mismos que son atributos solo para miembros de comité).

2022-11-12 17:51 UTC, Adrian-Garcia requested changes
Muy útil y funciona bien. Solo hay un bugsito chiquito y una sugerencia que creo que ayudaría a la experiencia del usuario pero en general está perfecto.

2022-11-12 17:51 UTC, Adrian-Garcia commented on .gitignore
> +/public/packs
¿Para que son estos? 🤔

2022-11-12 17:51 UTC, Adrian-Garcia commented on app/models/committee_member.rb
> +    belongs_to :user
Lo correcto es tener esta relación así como la cambiaste. Peeeero, no sé si en otras partes de la aplicación se esté usando el `CommitteeMember` como un `has_one` y al cambiarlo a `belongs_to` se rompan cosas de la aplicación (Ojalá hubieran pruebas unitarias para probar esto más fácil).
¿Serías tan amable de revisar que aquellos lugares en donde se usa un `CommitteeMember` funcione correctamente? Revisa las vistas, busca donde se usen commitee_members, que todo funcione correctamente, cosas así.

2022-11-12 17:51 UTC, Adrian-Garcia commented on app/views/committee_members/_form.html.erb
> +          <%= form.label :can_approve_committee_members, "Puede aprobar" %>
Creo que valdría la pena poner la información básica individual del miembro del comité como nombre, apellidos, roles, etc.

2022-11-12 17:51 UTC, Adrian-Garcia commented on app/views/committee_members/index.html.erb
> +</table>
¿Sería posible que pusieras una linea vacía al final de todos los archivos? Es buena práctica y así github no se enoja y nos pone estas alertas feas pidiendonos el salto de linea al final del archivo 
![Screenshot from 2022-11-12 11-49-04](https://user-images.githubusercontent.com/31387681/201487687-5fe7b6a1-6f6b-4269-9107-3d4d105a374a.png)

2022-11-12 19:29 UTC, Adrian-Garcia requested changes
![image](https://user-images.githubusercontent.com/31387681/201491336-62bbc90c-d398-4097-8d33-0dac20d70652.png)

2022-11-12 19:29 UTC, Adrian-Garcia commented on app/views/users/_form.html.erb
> +      <% if current_user.can_update_users? and user.judge_or_professor_pending_approval? and user.committee_member.can_approve_committee_members %>
Aquí me truena porque un usuario no tiene un método llamado `commitee_member`. En teoría lo mejor es que se acceda así... Pero no sucede lol. Así que para accesar al miembro del comité de un usuario lo debemos hacer de la siguiente manera 
```suggestion
      <% if current_user.can_update_users? and user.judge_or_professor_pending_approval? and user.committee_members.first.can_approve_committee_members %>
```

![Screenshot from 2022-11-12 13-20-58](https://user-images.githubusercontent.com/31387681/201491166-7932dfe6-94a8-4e31-b8cb-53cf7d92afc6.png)

También tienes que validar que el usuario sí tenga un mimebro del comité asociado así que si pudieras crear un método en el archivo `user.rb` llamado `can_approve_committee_members` el cual se dedique a validar esto estaría con ganas:
```ruby
def can_approve_committee_members
    return (self.committee_members.first.present? and self.committee_members.first.can_approve_committee_members)
end
```

2022-11-23 21:51 UTC, JeG99 commented on .gitignore
> +/public/packs
Está rarísimo, no toqué este pex en lo absoluto. 
De hecho está curiosón que se copia por cada commit.
![image](https://user-images.githubusercontent.com/43384949/203652004-f6a3f7ad-531a-45de-9587-0f6a47f02a1d.png)

2022-11-25 08:22 UTC, JeG99 commented on app/models/committee_member.rb
> +    belongs_to :user
Aquí mejor regresé esto a has_one, creo que no hubo muchas consecuencias

2022-11-25 08:23 UTC, JeG99 commented on app/views/committee_members/_form.html.erb
> +          <%= form.label :can_approve_committee_members, "Puede aprobar" %>
Agregué nombre completo y departamento en caso de ser profe

2022-11-25 08:23 UTC, JeG99 commented on app/views/committee_members/index.html.erb
> +</table>
Listo:P

2022-11-25 08:24 UTC, JeG99 commented on app/views/committee_members/_form.html.erb
> +      <% if current_user.can_update_users? and committee_member.user.professor? or committee_member.user.judge? or committee_member.user.committee_member? %>
Listo lo de juntar esas validaciones, pero lo de validar si contiene un usuario lo hice con otro método

2022-11-25 08:28 UTC, JeG99 commented on app/views/users/_form.html.erb
> +      <% if current_user.can_update_users? and user.judge_or_professor_pending_approval? and user.committee_member.can_approve_committee_members %>
Oye esto estuvo bien raro, supongo que fue por algún merge? Igual tuve que adaptar todo el avance de la página de comité para que vuelva a jalar, agregué un método a al modelo user.rb y otros al de committee_member.

2022-11-25 22:14 UTC, Adrian-Garcia commented on .gitignore
> +/public/packs
Ta raro 🤔 Dejalo así y más tarde haré un PR para arreglar esto

2022-11-25 22:15 UTC, Adrian-Garcia commented on app/models/committee_member.rb
> +    belongs_to :user
¡Naiz!

2022-11-26 19:59 UTC, Adrian-Garcia approved these changes
Todo kul

2022-11-26 19:59 UTC, merged